// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.21.12
// source: room.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";
import { BaseResponse } from "./utils";

export const protobufPackage = "room";

export interface RoomInfoResponse {
  success: boolean;
  message: string;
  name: string;
  users: string[];
}

export const ROOM_PACKAGE_NAME = "room";

export interface RoomClient {
  join(request: Empty, ...rest: any): Observable<BaseResponse>;

  leave(request: Empty, ...rest: any): Observable<BaseResponse>;

  getRoomInfo(request: Empty, ...rest: any): Observable<RoomInfoResponse>;
}

export interface RoomController {
  join(request: Empty, ...rest: any): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  leave(request: Empty, ...rest: any): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  getRoomInfo(
    request: Empty,
    ...rest: any
  ): Promise<RoomInfoResponse> | Observable<RoomInfoResponse> | RoomInfoResponse;
}

export function RoomControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["join", "leave", "getRoomInfo"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Room", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Room", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ROOM_SERVICE_NAME = "Room";
